<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	 <ScopedCssEnabled>true</ScopedCssEnabled>
    <UserSecretsId>aspnet-ChessGameBlazorClient-25febf3c-eac8-4c2e-a74f-33e97d398729</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.19" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\ChessGameContracts\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChessGame.Infrastructure.Infrastructure\ChessGame.Infrastructure.Infrastructure.csproj" />
    <ProjectReference Include="..\SharedResources\SharedResources.csproj" />
  </ItemGroup>

</Project>
