services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Karokar3.
      - MSSQL_PID=Developer
      
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Karokar3. -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10 
      start_period: 20s 
        
    ports:
      - "1433:1433"
  
  gateway.api:
    image: gatway.api
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - ASPNETCODE_ENVOIREMENT=Development
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    ports:
      - "7124:8081"
        
  migration-helper-chessgameapi:
    build:
      context: .
      dockerfile: webAssemblyChessGame.Services.ChessGameAPI/Dockerfile
      target: build # Targets the stage where we installed dotnet-ef
    depends_on:
      sqlserver:
        condition: service_healthy
    # Make sure to use the full command path if needed
    command: dotnet ef database update --connection "Server=sqlserver;Database=master;User Id=sa;Password=Karokar3.;TrustServerCertificate=True;"
        
  migration-helper-blazorclient:
    build:
      context: .
      dockerfile: BlazorServerSideClient/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    command: dotnet ef database update --connection "Server=sqlserver;Database=master;User Id=sa;Password=Karokar3.;TrustServerCertificate=True;"
  
  cheessgame.api:
    image: chessgame.api
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - ASPNETCORE_ENVOIREMENT=Development
    build:
      context: .
      dockerfile: webAssemblyChessGame.Services.ChessGameAPI/Dockerfile
    ports:
      - "5203:8081"
  
  blazor.clinet:
    image: blazorserversideclient
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - ASPNETCORE_ENVOIREMENT=Development
    build:
      context: .
      dockerfile: BlazorServerSideClient/Dockerfile
    ports:
      - "5191:8081" 
    depends_on:
        - sqlserver