services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Karokar3.
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"

  gateway.api:
    image: gateway.api
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7124:8081"


  chessgame.api:
    image: chessgame.api
    build:
      context: .
      dockerfile: webAssemblyChessGame.Services.ChessGameAPI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5203:8081"

  blazor.client:
    image: blazorserversideclient
    build:
      context: .
      dockerfile: BlazorServerSideClient/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5191:8081"
    depends_on:
      - sqlserver