<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>aspnet-ServerSideClientUI-c80de7a6-395f-41cb-915a-66fb7a2c5fd9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\ChessGameContracts\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdentityService.Domain.Domain\IdentityService.Domain.csproj" />
    <ProjectReference Include="..\SharedResources\SharedResources.csproj" />
  </ItemGroup>

</Project>
